jobs:

# Job with minimal dependencies, to make sure that tests relying on
# optional dependencies get skipped.
- template: azure-template.yml
  parameters:
    os: linux
    name: LinuxMinDependencies
    displayName: Linux with minimal dependencies

# Now try with all optional dependencies. We also include the --readonly
# flag to make sure no files are being written to the temporary install
# location during testing.
- template: azure-template.yml
  parameters:
    os: linux
    name: LinuxAllDependencies
    displayName: Linux with all dependencies
    pip_args: .[test,all]
    command: test --remote-data=astropy --readonly --coverage

# Run with the oldest supported version of Python and Numpy
- template: azure-template.yml
  parameters:
    os: linux
    name: LinuxOldDependencies
    displayName: Linux with oldest version of dependencies
    python: 3.5
    pinned_dependencies: numpy==1.13.3

# Include a MacOS X build
- template: azure-template.yml
  parameters:
    os: osx
    name: MacOSXAllDependencies
    displayName: MacOS X with all dependencies
    pip_args: .[test,all]

# And a Windows build
- template: azure-template.yml
  parameters:
    os: windows
    name: WindowsAllDependencies
    displayName: Windows with all dependencies
    pip_args: .[test,all]

# Documentation build
- template: azure-template.yml
  parameters:
    os: linux
    name: LinuxDocumentation
    displayName: Documentation build
    pip_args: .[docs,all]
    command: build_docs -w

# Visualization tests with pixel-by-pixel image comparisons

- job: VisualizationMatplotlib
  displayName: Visualization tests
  strategy:
    matrix:
      mpl202:
        version: 2.0.2
        image: astropy/image-tests-py35-mpl202:1.4
      mpl212:
        version: 2.1.2
        image: astropy/image-tests-py35-mpl212:1.4
      mpl222:
        version: 2.2.2
        image: astropy/image-tests-py35-mpl222:1.4
      mpl300:
        version: 3.0.0
        image: astropy/image-tests-py35-mpl300:1.4
  pool:
    vmImage: Ubuntu 16.04
  container: $[ variables['image'] ]
  steps:
  - script: python3 setup.py test -P visualization --remote-data=astropy -a "--mpl"
    displayName: Running tests

- job: VisualizationMatplotlibDev
  displayName: Visualization tests (Developer Matplotlib)
  pool:
    vmImage: Ubuntu 16.04
  container: astropy/image-tests-py36-base:1.1
  steps:
  - script: sudo apt-get install -y libfreetype6-dev libpng12-dev pkg-config
    displayName: Install apt dependencies
  - script: pip3 install "pytest<3.7" pytest-mpl pytest-astropy numpy scipy git+https://github.com/matplotlib/matplotlib.git
    displayName: Install Python dependencies, including developer version of Matplotlib
  - script: python3 setup.py test -P visualization --remote-data=astropy -a "--mpl"
    displayName: Running tests

# 32-bit Linux tests

- job: Linux32
  displayName: 32-bit Linux tests
  pool:
    vmImage: Ubuntu 16.04
  container: quay.io/pypa/manylinux1_i686
  steps:
  - script: /opt/python/cp35-cp35m/bin/pip install numpy scipy pytest pytest-astropy pytest-xdist Cython jinja2
    displayName: Install dependencies for Python 3.5
  - script: PYTHONHASHSEED=42 /opt/python/cp35-cp35m/bin/python setup.py test --parallel=4 -a "--durations=50"
    displayName: Run tests for Python 3.5
  - script: /opt/python/cp36-cp36m/bin/pip install numpy scipy pytest pytest-astropy pytest-xdist Cython jinja2
    displayName: Install dependencies for Python 3.6
  - script: PYTHONHASHSEED=42 /opt/python/cp36-cp36m/bin/python setup.py test --parallel=4 -a "--durations=50"
    displayName: Run tests for Python 3.6
  - script: /opt/python/cp37-cp37m/bin/pip install numpy scipy pytest pytest-astropy pytest-xdist Cython jinja2
    displayName: Install dependencies for Python 3.7
  - script: PYTHONHASHSEED=42 /opt/python/cp37-cp37m/bin/python setup.py test --parallel=4 -a "--durations=50"
    displayName: Run tests for Python 3.7
