jobs:

# Job with minimal dependencies, to make sure that tests relying on
# optional dependencies get skipped.
- template: azure-template.yml
  parameters:
    os: linux
    name: LinuxMinDependencies
    displayName: Linux with minimal dependencies

# Now try with all optional dependencies. We also include the --readonly
# flag to make sure no files are being written to the temporary install
# location during testing.
- template: azure-template.yml
  parameters:
    os: linux
    name: LinuxAllDependencies
    displayName: Linux with all dependencies
    pip_args: .[test,all]
    command: test --remote-data=astropy --readonly --coverage

# Run with the oldest supported version of Python and Numpy
- template: azure-template.yml
  parameters:
    os: linux
    name: LinuxOldDependencies
    displayName: Linux with oldest version of dependencies
    python: 3.5
    pinned_dependencies: numpy==1.13.3

# Include a MacOS X build
- template: azure-template.yml
  parameters:
    os: osx
    name: MacOSXAllDependencies
    displayName: MacOS X with all dependencies
    pip_args: .[test,all]

# And a Windows build
- template: azure-template.yml
  parameters:
    os: windows
    name: WindowsAllDependencies
    displayName: Windows with all dependencies
    pip_args: .[test,all]
