version: 2

jobs:
  rtd:
    docker:
      - image: readthedocs/build:2.0
    steps:
      - checkout
      - run:
          name: Create conda environment
          command: conda env create --name latest --file .rtd-environment.yml
      - run:
          name: Install standard RTD dependencies
          command: conda install --yes --name latest mock pillow sphinx sphinx_rtd_theme
      - run:
          name: Install pip dependencies
          command: pip install -U recommonmark readthedocs-sphinx-ext
      - run:
          name: Install package
          command: python setup.py install --force
      - run:
          name: Show conf.py
          command: cat docs/conf.py
      - run:
          name: Run HTML build
          command: sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
      - run:
          name: Run JSON build
          command: sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json

workflows:
  version: 2
  build_and_test:
    jobs:
      - rtd
