version: 2

jobs:
  rtd:
    docker:
      - image: readthedocs/build:latest
    steps:
      - checkout
      - run: python setup.py egg_info


workflows:
  version: 2
  tests_and_docs:
    jobs:
      - rtd
