name: Weekly cron

on:
  schedule:
    # run every Monday at 6am UTC
    - cron: '0 6 * * 1'
  pull_request:
    # We also want this workflow triggered if the 'Extra CI' label is added
    # or present when PR is updated
    types:
      - synchronize
      - labeled
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IS_CRON: 'true'

jobs:

  tests_more_architectures:

    # The following architectures are emulated and are therefore slow, so
    # we include them just in the weekly cron. These also serve as a test
    # of using system libraries and using pytest directly.

    runs-on: ubuntu-20.04
    name: Python 3.9
    env:
      ARCH_ON_CI: ${{ matrix.arch }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: ppc64le

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: uraimo/run-on-arch-action@v2
        name: Run tests
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu_latest

          shell: /bin/bash

          install: |
            apt-get update -q -y
            apt-get install -q -y git \
                                  g++ \
                                  pkg-config \
                                  python3 \
                                  python3-configobj \
                                  python3-numpy \
                                  python3-ply \
                                  python3-venv \
                                  cython3 \
                                  libwcs7 \
                                  wcslib-dev \
                                  libcfitsio-dev \
                                  liberfa1

          run: |
            python3 -m venv --system-site-packages tests
            source tests/bin/activate
            ASTROPY_USE_SYSTEM_ALL=1 pip3 install -e .[test]
            python3 -m pytest
