name: Auto-update IERS tables

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Checkout new branch
      run: git checkout -b `date --iso-8601=seconds`
    - name: Download latest IERS files
      run: ./update_builtin_iers.sh
      working-directory: astropy/utils/iers/data
    - name: Commit changes
      run: |
        git config user.name 'Astropy Bot'
        git config user.email 'bot@astropy.org'
        git add astropy/utils/iers/data/Leap_Second.dat
        git add astropy/utils/iers/data/eopc04_IAU2000.62-now
        git commit -m "Update IERS Earth rotation and leap second tables"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: update-iers-
        branch-suffix: timestamp
        labels: backport-v5.0.x
        title: Update IERS Earth rotation and leap second tables
        body: This is an automated update of the IERS Earth rotation and leap second tables. Feel free to merge if the CI passes!
